language: ruby
rvm:
- 1.9.3
test:
  override:
  - echo OK
before_script:
- git config --global user.name "ngs"
- git config --global user.email "a@ngs.io"
- git remote set-url origin $REPO.git
- if [ -z "$id_rsa_{1..32}" ]; then echo 'No $id_rsa_{1..32} found !' ; exit 1; fi
- echo -n $id_rsa_{1..32} >> ~/.ssh/travis_rsa_64
- base64 --decode --ignore-garbage ~/.ssh/travis_rsa_64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- rake setup_github_pages[$REPO]
script:
- rake generate
after_script:
- rake deploy
env:
  global:
  - REPO="git@github.com:ngsio/ngsio.github.com.git"
  - secure: WirpvJXCwhax3lNZFtEG+WcSPYedXsjRFL0RjzmEKxHrIJe/viJLVgzYHa0cWKYpEAGPNXfEcIG/Z1ckgx83ryuNR1ahtsr9IMIMGgNCCwVwgATzeuqymgOJS3QRD3QqyI+gU8DI7GsE2C8Wfy7ynAGfWIdq6M8SR0unANui15A=
  - secure: IAkV7HCJZI68HXbeFbX4odRCgaC5ikgMaykUg6S1h6iBSCFVA0TVteMI4gdaa89Xxo8YbFVXLSCfRZ85IWmgzneQbNAv2oxZLnNo+Ap7JdmzcM2qVp8gt1PrRJqVwGrSupXfVPfbauhTfwyC+J/VsBKPGqhbv19pHJ7Hi7vkcBI=
  - secure: Xja5PFBIfDMcd7/oYiSO+wb/B+RZavkTUHsvTnLJgPTWGLXmAv2xXEL71xkkw2r66DDOX3sibP8NEEkFp32jmJfUyKlCgs+mQG/dcCpa8iGYKdiSOiKcmgpWCPGWx8zWOlXC1/IOFegtLBZal4CJ46FvRNU1N02Mh66FcdcqxWk=
  - secure: kYxtHiO1MKUMbdnfEEJtcjOrsfthIw5MhYg/inAfXc5xKi1JDSS9ldrGKxynKcACOEy7ckE7iEwbq2dgPo50UitV71qQa1VS6x5ENmgobYIBX37zrNSxmSk84OfOKnjcxEO3oKoCtD9GS4+FAqx3gWDkF0GePkoQ4Wulrb7PoQg=
  - secure: APZHzpTS5jlu/DwoIQLiPcFMc0WHEIqIxe3BkzYXtJdZV3h0i+TG5HnkFpiHY8gzQXHNhcziYh8csPr2ushtwf0fgBXn1UghTsS1HyRbBuwq0IgW2FClwoUePTxPjGah851bDYe+t4ZflnmEs/ImyeeqGo0KhKY0n2fKWMqIcew=
  - secure: hFqrecrnOLV9vpHyMbyT7D1e81908Z6Ujw26RCMneGoMSTVLjOqXujpr473EZKelvNimYqFHIiyiX0hlD75j3y3WZgYP9AYMuFhxnY9XytYDFVtHG51fBAGRNvBI4W20/svEDKKdjt9Mrp+0Og1C5AKMLpSupjAxpU56FzWt7fY=
  - secure: erjdzFxe5S0Crt17m9ZdafEnjDvff7CHDjKeG1oPap50wC36xfH1gvbXUQOK4pcN7JLNIG5JmgN5Wwjl9XVI6YPTj7mlM/QX8dFvGfrKRhdoe57iP5awpHnk8AOeeyj7Z5LxBqMOg2ny+9M97L4aU1m8TepyCfYUmA2/yqCe/Lo=
  - secure: HmabX+6agTJYc08P/8Y1fqAZXv4oTNpaFV85q+AQmJNmo/eBDN3k89I1E0oez0l1pPSre1np/1NzeAg8IucrzfoBeusfyg89rIfO6rdeOTSxclWkq8n+q1MRhJrzXhZ2mUZRsm6icPCE8XAdFJf4Vz20f2LhVZWtjCKtoGkEg8Y=
  - secure: LcusdMOSnZp4M/xB4EMq0egtz+B/Gvt12i3b4r1Kx157Pvy3BMyXDybtM2FKNKF5NlxSFX5hyesGhvUwe0FlzPDZp1Tz23Yfzwfthmhnpb6fqKMrPi56hHpxmAENzbMyMIRzG3HNZXqTcMh9ZDUcZGr6+O4jBLKo4KBKt/E859E=
  - secure: kxnJh3XpwcxK4ion8MQs1kFw4GG1QLkW2LMtUf8Q8h79Zchp4Pl1gGDkxk+9eCwKe9hquy8/Q5PvsOFjjSL2vQGsLG5hO7C37TpzCaxzkFuTteZWndLZvcqkHfHaNb2Nn8xZ+BP3/1FIeXwdbfd12Sa9VasTBlW2HiphiGT2JuQ=
  - secure: lTgzZC0+9uIsSIBMpNavNwMLWGkeTZgvf2COfvGU8spxOR3gkhAzh1BP7+YaaMd4uAwFj8c2p3UFU29nkXLMQd4dtBpROJGCRzvBftZTwd8389uvlOiqb1UyMCzoa14nz+e9VfQQFZsQU2/zf+VoGDseXacL4e8YSS4f4OJQDKM=
  - secure: PxtNbOoS+JCeOZlrM6e3LugXHusp3LHTUTU4QhS+IUlorvUzD5k0eR7Xjl+U7q3NwOjUTlJW9A3ZdTZNF7oI27eIv+Kc/DtnJU1pZ8y30CvRf7DeFjNIaETjvEaS44LUcUDRsckhk8CSIQzXoC7j+tsMo0+XFWC2BeJIMIS72uo=
  - secure: aIj2hHjJS3b+ybIx16yzKkHJinolu0QuUvShutSyRbFPk6XZHvVyOnRyKU8+fj+N6Y4N3whmjQEFsvFdj//UTwwPdZ1uxD7WsNuj+kLyWb0hJMwocy5YN8GqSxpaEfVVph4PieHBmlDNo5CV5r5BUa9N9QGN27mOXpKSniFTMhI=
  - secure: WJUW97ipOLlwm2FKIh1iURSeOTShFaX6k0mBnT8K+QKSb1MYMqZZ8Cua67ToD53ff1j+hvnDAGqluDvjFZv7sezRfC9GCdRvMP6AuGJlGMbGE0bMSm5pnMTDwD1atQL5lighyRKkuvqejxj7+b81/0AaoKvACDZ1afqDz/Mn//M=
  - secure: TJOIg0nV34TYXbN8ZbblxjBdPKVC6N8viSBX46qfshD2sPDdO7MEi1j0/jXdmAvnPlZYuq2ObeDYJTicEqxCiOvcjI/cGM71LsP0JtpgOYgyS5aDe/xZJ7KoMxMDNup3wUjPjBdh/sZlgl3lilWUhs7GOSvgEy5RcJTHt/s1fg8=
  - secure: LjyRX3DXdTJijNNAZHj7Cs4jEP6Fs6kqCklwd17mGDv56axfCzYhis4hf9AWi4Ev+7VEFRALummTRLOy1N3VpcM1qkGsXqoLimTNq6phiZ7qdXAJD1A2vRxu+8Asu7khYcKQOOmy3lQPa5aouYc8PRPIxPjBPzDaCJjzvugFP5w=
  - secure: PoCl7Y5Gq07n3CqgxovnaBGI2+zm/7AW5PztKzWUXH0FteG9UJtdS3pC7O2pcnHbCRihClRN/JQQanYNT4H27kf6YrYxCWKrawepVRwM1Sw0hWhqDzIosjwKK8LuOcgUp2FXsVFy18Z5shr4rPQ4QjNfdKP5efcOzv4gjaCxleQ=
  - secure: jGqQFJojlXwpaPJBfxxBgVJNya41V06B09W233ftrb17cSs4Mv3G9sO7RrElCXTRXvDJRFCVv20y/elGPHTRxv1g9FiRq2lVnqAOThVOcRGmQ6GZqB7LOUrBns4Ni13RmF65kRIx60Q2rxLMDyCQUEYYX/mDLnh4bkr8gFERnrU=
  - secure: B3Fj7am5VDrmDN1rp2jDcfHORgcjxhcqycFThrn2X75paV3AAmqfeVxh2dfyb46vA/SKdoh6IEqfG+rrgMAzlW2weACshBYpW01wPd0Hl+nnQJ7h9+VEc3rPb7vJPFNy9QXlCD7d+AcfmOhSsW6leOXag6sONcdRfLD7Avk39Ms=
  - secure: JKF3EIFRMhufKiCr8EveVBpZWZTYzdmab57mzSKEuycgx77MPLL1dBTTOR+Eh6sigQFQGA54dKKlVeajVE6q643cbTDVfPZDIp49F1oRG/dtqpuzptN461vBObq71CNFmpWvp7mjxRyE3cGn7u0mO7KYyVtQTaoC7PZiR6BCjK4=
  - secure: A10hPHtH/uugsI9rP2o7Cg/anSkSb1kqCsKhIYE6sLsLAWwXNPfpClEGzYd3695b1eUMl2vOwwSA2oiQ0YSw2XzCPogo3rseSId8pNlqLCNaQvfbYImx1U888Pl9c6SdPG6B088E4znEg42tSUag0Sng1hECYBQo5tcbe2T0HtY=
  - secure: eiyhVQrmHmqjSkCzTwfBBIdQC5SFBHrYOSP+qfsv4/J4xsdmJFaZ1YBAbUUEfg+xvUQXc+haHV5iSjgcKqidsGyohn0nTONoZ5+HM2q2H3bh4ruTzOctgl2hR/bTxo1g4My0CWKvy2zNMuSJGi/ysu4oCvs7IiW8KHGEhNFP02I=
  - secure: iTWiyehjt4pHPZP60cINlBKG3tnC+Xco0SYDDyCCG78GJdHrzUrAy7FzCkYXK6W1lJCS94IId3RwQvH3quloFmCkyrcEPJyWqr9j02XltrgwGWD15dR/yayUAbxyljln1QZvSnJo5MXzVkeV0qh0hRfhB/Llda0IQHBisVqcwPg=
  - secure: WrKZy+nfF6Lvsbsoa0TGyiJJXF/FA7clXK4l/VUIXxkQtlRbQgohBF7SRXV6w52wk4R+OjIJSa17rn9A12ybg3FDQS7SHNd4J4Z82LOpVuqW2BM5Kx8XRoGeTt6p1m8y690vfEvOHcHzKH84ojOfd+bkl91NHQBKkZZKA5gEi2I=
  - secure: g0nhTBx8aCJue31U+JomZz74+DzzHydAy8BpPzQNQCkkfEZKWBV2/QSMc9fFgd2jB4Ztu5rXsgEcTJw52TBq031gcJcVseZCzjl8gDaI1ITz7yf5HJidcrcRHP7vbMglpBhJMHxaoqMNgYmS0HmAHQEcdTi2KfDIpgv0ZRxGQB8=
  - secure: iea1hegGBeSkF+36vzbmiUfgixeyWiR/hkitTmy9LQPQtq4+7Y3ESMoxFQaVQhoY2ln1cMvSgNW6J3E8BcTcldASPEj5XgA3ebKe1brGeS5Fg9iDiO4M68xwlsbNXP3sEWJ2cTp0aNAn8o9wsee8HCClRzYnjEjzyAGaDET6b3I=
  - secure: QHqUJGDmX1qTie5Pjlrb9qhYf+Ao30YUxNi24ZgNiAlLyjKYpl4dCGGoRe41fdZb5EF9sbGZqiBTiBBZjJ2repkFs4WgA7FvYhQwi3HRqFMiurPOZJZfUchdYa+TgraqaFvyI3TF5uHCo+5rM5JzyXGeG80Lfeljc7YaMpDUzVo=
  - secure: f5vUL2/06qfVzUYnxTOTrjslnyMbouhGtakHmd7qFZy6ucwNWKT+guAw1wevb8unQbZ5kdK+/RuRyCtNEtM7m7v93eQZCL7MtzeF70I8urF1ZW/lyTHO0vYnCbpn22yaw2Q1FyS8xtmTEZvmFZZH6g/BJKKzbvJALW3/CWPmsFA=
  - secure: Ny4iS97xA3sf8GdC+aeRKNTpUdCw0/9vwxS3U9ar9vG6MdRXeiVqM0WBCtCh1z6SrJvyYDE/H0mwiT6Tv0UhCLoDfcfIEuyg/sXGrXqNnZKQlkozm1xeXswB5alzEZOYMPReUmo9r7KQ3GKTQ0mjecXCaOOOP+bNSP8IrDegQVo=
  - secure: lwDV/XzoPKC1FShuTNDtwpwWa8iBllRM327vSIY/lJB3AhaYNV6VW1Gi839d65pUsMXA8C9BTnT1hBBwpYlcIyHZPJd3vX1haJWP2jSUoyLFJRGAaQ09StxCCXgJcna31Fxv4mp27n7J8Vqhy4iTcWvS94zm2zwWmbTQro6hoaE=
  - secure: F99kqmXs5nVxMTucPHbfTlYXSzf1nlAammGHNdlTktpt1kr6Msun5+Jy5nh0bxvB6fF5I1RSQt9WVoZvxFMeb6GMVLK1KEQ9yH9n0LKkzy2+/BtWtT7kbBjY2Ks99k/vLnrxqCftDzWhQB6yvlE+v6FuupQ7m5i3MGLbF4Y0sEI=
  - secure: e7o+l6vR7H82naKpaDOoB9V+oQuuJh0aZvlFeIj9tz/DMB6t80ew2w6rG154jJNe6w/dUBaS22VfA1vktwrmCdWWBUINstNgHUKK6/f+N0RVQnYTWicZq7WyiaNm8IUtSm86B9E6poLujl3vxK/We4HtHaN5ZMc5s/edLu96mJM=
