---
language: ruby
cache: bundler
script: bundle exec middleman build
env:
  global:
    - GIT_COMMITTER_NAME='ngs@travis-ci'
    - GIT_COMMITTER_EMAIL='a+travis@ngs.io'
    - GIT_AUTHOR_NAME='ngs@travis-ci'
    - GIT_AUTHOR_EMAIL='a+travis@ngs.io'
    - secure: "edQutmTwVQx14lVl8e6XmiAiZHASVzvrIb+X9/IBYl6muawTj7ZdvVQd9R9V0l9MVwxU7EWiFXXbw9f1RNBFFavKZm4A193K18+rsYAFCn4wfR+qY5XkQHfokcMIo2SU5aElJiSjegxYGdqakm91EQinl3yUCEeDlS5UNN8AZQk="
after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && cd $TRAVIS_BUILD_DIR/sites/ja.ngs.io && bundle exec middleman deploy'
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && cd $TRAVIS_BUILD_DIR/sites/ngs.io && bundle exec middleman deploy'

