---
language: ruby
rvm:
  - 2.0.0
cache: bundler
script: bundle exec middleman build
env:
  global:
    - GIT_COMMITTER_NAME='ngs@travis-ci'
    - GIT_COMMITTER_EMAIL='a+travis@ngs.io'
    - GIT_AUTHOR_NAME='ngs@travis-ci'
    - GIT_AUTHOR_EMAIL='a+travis@ngs.io'
    - secure: "UcV3qTN87+aWcpEZL61QGXH5stFj2WUbHQwZZiXqxCv0+YNZv4S6bZzPi6oponGbe+DSGLCZmFhIuP2Ckmc2eRC2X3DRPCb0wBXcQ1TnUWb/IHqloHpUXdyZUWY563i8LuoRZ9hdUUjvIwa5X6JbcdyB3e9vWW2/kgqZXjLOK34="
env:
  matrix:
    - MM_LANG=ja
    - MM_LANG=en
after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && bundle exec middleman deploy >/dev/null 2>&1'
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && bundle exec middleman deploy >/dev/null 2>&1'

