bundler_args: --without development --path=~/.bundle
language: ruby
rvm:
- 2.0.0
env:
  matrix:
  - MM_LANG=ja
  - MM_LANG=en
  global:
  - TAGGER_DIR=~/.bundle/tree-tagger
  - TREETAGGER_COMMAND=$TAGGER_DIR/cmd/tree-tagger-english
  - BUNDLE_ARCHIVE='ngs.io'
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- gem install bundler fog
- /bin/sh ./script/travis/bundle-install.sh
# - sudo apt-get -yV install mecab
# - sudo apt-get -yV install mecab-ipadic-utf8
- /bin/sh ./script/install-tagger.sh
script: bundle exec middleman build
after_script:
- ruby script/travis/bundle-cache.rb
after_success:
- '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && bundle exec middleman deploy >/dev/null 2>&1'
notifications:
  on_success: always
  on_failure: always
  on_start: always
  webhooks:
    - 'http://ngs-hubot.herokuapp.com/travisci/hooks'

